### ISSUE TITLE
Brace formatting breaks startup

### ISSUE THREAD

**Issue by guyrish** [robohydra/robohydra#16]
Adjustments in bracing cause plugins to fail.

Failing formatting:

![index bad](https://cloud.githubusercontent.com/assets/14807152/10049936/7b4ea612-61df-11e5-9be2-1653617549c4.jpg)

Working formatting:

![index good](https://cloud.githubusercontent.com/assets/14807152/10049940/7ff853c0-61df-11e5-8682-8a471f9f7705.jpg)

Stack dump at startup:

C:\Program Files\nodejs\node_modules\.bin>robohydra -n -P formaterror
C:\Program Files\nodejs\node_modules\robohydra\bin\robohydra.js:98
            throw e;
                  ^
TypeError: Cannot read property 'scenarios' of undefined
    at RoboHydra._inflatePlugin (C:\Program Files\nodejs\node_modules\robohydra\lib\RoboHydra.js:407:48)
    at RoboHydra.registerPluginObject (C:\Program Files\nodejs\node_modules\robohydra\lib\RoboHydra.js:176:41)
    at C:\Program Files\nodejs\node_modules\robohydra\lib\robohydrasummoner.js:106:19
    at Array.forEach (native)
    at RoboHydraSummoner._createHydra (C:\Program Files\nodejs\node_modules\robohydra\lib\robohydrasummoner.js:105:29)
    at RoboHydraSummoner.summonRoboHydraForRequest (C:\Program Files\nodejs\node_modules\robohydra\lib\robohydrasummoner.js:96:38)
    at createRoboHydraServer (C:\Program Files\nodejs\node_modules\robohydra\lib\robohydraserver.js:87:14)
    at C:\Program Files\nodejs\node_modules\robohydra\bin\robohydra.js:82:18
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\robohydra\bin\robohydra.js:118:2)
    at Module._compile (module.js:460:26)

**Comment by emanchado** [comment]
I don't think this is a flaw in RoboHydra at all, this is a flaw/peculiarity of JavaScript :-( If I'm not mistaken, the "new RoboHydraHeadFilesystem" line will create a really strange, broken object and that's probably why you're getting the error...

See Automatic Semicolon Insertion (ASI) here: https://en.wikipedia.org/wiki/JavaScript_syntax#Whitespace_and_semicolons
