### ISSUE TITLE
proxyTo from behind corporate proxy not working

### ISSUE THREAD

**Issue by drcabana** [robohydra/robohydra#3]
Hi,

I am trying to use the proxyTo feature from behind a corporate firewall and squid proxy.  So far I have not been able to make things work. I suspect the problem is because of  interactions with the  squid proxy.  

I simplified the duckduckgo example the comes with RoboHydra, as follows:

var RoboHydraHeadProxy      = require("robohydra").heads.RoboHydraHeadProxy;

   exports.getBodyParts = function(conf) {
       return {
           heads: [
               new RoboHydraHeadProxy({
                   mountPath: '/duck',
                   proxyTo: 'http://duckduckgo.com'
               })   ]   };  };  

When I visit localhost:3000/duck I get a 502 error.  Here a the request/response headers:

GET /duck/ HTTP/1.1
Host: localhost:3000
Connection: keep-alive
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/535.19 (KHTML, like Gecko) Ubuntu/11.10 Chromium/18.0.1025.168 Chrome/18.0.1025.168 Safari/535.19
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Accept-Encoding: gzip,deflate,sdch
Accept-Language: en-US,en;q=0.8
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.3

HTTP/1.1 502 Bad Gateway
server: squid/2.7.STABLE9
date: Mon, 23 Jul 2012 15:14:09 GMT
content-type: text/html
content-length: 980
x-squid-error: ERR_ZERO_SIZE_OBJECT 0
x-cache: MISS from transproxy.unx.sas.com
x-cache-lookup: MISS from transproxy.unx.sas.com:3128
connection: close

Any ideas on how I might get this to work?  I suspect I m not the only user working behind a proxy.  Any help would be appreciated. 

Additional notes: I turned off the firewall on my local machine, that made no difference.

Yours,
David Cabana

**Comment by weslien** [comment]
this is still a relevant question :)
playing nice with proxies is key for enterprise adaptation and is, in general, a weakness across the board in node world.

**Comment by emanchado** [comment]
I had forgotten about this, thanks for the reminder. Could you please help me test the direct-proxy-support branch? https://github.com/robohydra/robohydra/tree/direct-proxy-support

It should work just by setting the "http_proxy" and/or "https_proxy" variables. I don't have any proxy myself to really test this (I installed one locally but requests will go through even if I make mistakes), so I'd really appreciate help testing this with different combinations, like different request methods, uploading files, HTTP and HTTPS, etc.

If you can confirm this works well, I'll merge it to master and it will be available in the next RoboHydra release.

Thanks!

**Comment by emanchado** [comment]
@weslien: have you tried, does it work properly? If so, I'll merge it and document it and release a new version...

**Comment by emanchado** [comment]
Ping.

Can someone please confirm whether or not the fix works?

**Comment by RIAstar** [comment]
Hi @emanchado,

I just started trying out RoboHydra from behind a corp proxy, so I stumbled upon this thread.
I tried the `direct-proxy-support` branch, but unfortunately it doesn't work for me: I no longer get a 502 (as I did with `master`), but now I get a 407 (not authenticated). The response body contains our company's default 407 page.

You do mean to export the `http_proxy` OS environment variable, don't you? Or do I have to configure it somewhere in RoboHydra?

I haven't had time to dig into the code and find out what's going on. I hope I can make some, but that's uncertain :(

**Comment by emanchado** [comment]
Hi @RIAstar! I did mean the environment variable, yes. Does your proxy need some kind of authentication? Do you include that authentication in the value of the environment variable? Do other tools (eg. curl) work with that same environment variable?

If you get the 407 page I'm guessing everything is configured as I expect, so I'm not quite sure what to try next. I don't really have much experience with proxies so I'm a bit lost :-(

If you answer the questions above maybe we'll get some insights and we can try to poke further :-)

**Comment by RIAstar** [comment]
Proxies (and the people who enforce them) should die a slow and agonizing death. I spend more time working my way around them then getting real stuff done. Now with that out of the way ...

> Does your proxy need some kind of authentication?
Simple user / password authentication over http

> Do you include that authentication in the value of the environment variable?
Yup: `export http_proxy=http://user:password@proxy.domain:8080`
Note that neither my user name nor my password contains special characters; just alphanumeric and underscores. (Special characters sometimes cause trouble)

> Do other tools (eg. curl) work with that same environment variable?
Yes, curl and git for instance. Others like npm and bower read proxy info from a config file (`.npmrc` and `.bowerrc` respectively).

**Comment by RIAstar** [comment]
There's another related issue: when I try to reverse proxy an internal dev server (that is white-listed on the corp proxy) RoboHydra returns a 500.

Stacktrace:
```
TypeError: Request path contains unescaped characters.
    at new ClientRequest (_http_client.js:73:11)
    at Object.exports.request (http.js:49:10)
    at HttpsProxyAgent.createConnection (\node_modules\robohydra\lib\HttpsProxyAgent.js:17:24)
    at HttpsProxyAgent.createSocket (\node_modules\robohydra\lib\HttpsProxyAgent.js:87:10)
    at HttpsProxyAgent.addRequest (\node_modules\robohydra\lib\HttpsProxyAgent.js:59:14)
    at new ClientRequest (_http_client.js:154:16)
    at Object.exports.request (http.js:49:10)
    at exports.request (https.js:136:15)
    at proxyRequest (\node_modules\robohydra\lib\utils.js:175:24)
    at AbstractRoboHydraHead.handler (\node_modules\robohydra\lib\heads.js:468:17)
```

**Comment by emanchado** [comment]
I'm a bit lost now. I'll try to install a proxy and try a bit more at home, and will probably use some Node module for the proxying instead of trying to solve it myself.

I'm fairly busy ATM, though, so any help is really appreciated! I can guide you through the code if you want to give it a go and need the guidance (it's basically the proxyRequest function in lib/utils.js).

**Comment by emanchado** [comment]
I have made another branch using proxying-agent. I don't think NTLM authentication works, but the basic one seems to work fine, and the code is much simpler and nicer than in my first attempt (although there's one extra dependency now). Please give it a try and tell me whether it works for you:

https://github.com/robohydra/robohydra/tree/proxy-support-proxying-agent

If you do use NTLM authentication, give me a shout and I'll try to add that, too.

**Comment by emanchado** [comment]
@RIAstar? Have you had time to test this? If you confirm that this works I'll probably release a new version with this new feature.

**Comment by RIAstar** [comment]
Sorry, had no time to follow up (release last friday) and I can only test this in the office.
Hopefully next week will be calmer.

**Comment by emanchado** [comment]
Ping! Any news on this?

**Comment by emanchado** [comment]
OK, anyone that has interest in this bug: can you please test it and confirm that it works anywhere else apart from my machine?

**Comment by RIAstar** [comment]
Just tried that branch.
This time I get a 400 "Bad request" :(

I'm not sure whether we us NTLM or not. I think Kerberos is involved, but I know very little of these things.

**Comment by emanchado** [comment]
@RIAstar: is there any way you can confirm? NTLM seems kind of tricky to add, mostly because of the testing on my side.

Also, after reading a bit, I'd be slightly surprised if it was NTLM, if your proxy configuration is simply the http_proxy environment variable. And 8080 doesn't seem to be the default NTLM port :-/

Finally, are you able to debug the code a bit? It works on my side, so it's really hard for me to figure out what the problem is, or how to fix it. If you want, I can prepare a special version with extra logging that you can run and then paste the logging somewhere, so I have a bit more information.

**Comment by RIAstar** [comment]
I really don't have much time to allocate to this (we're not using this feature - yet). I'd personally like to help you close this issue, but I cannot reproduce at home :( 

So in short: running your "debug" version I can do; debugging the RH code myself unfortunately I cannot (unless I can come up with a use case for the `proxyTo` feature).

**Comment by emanchado** [comment]
Hi, I just pushed a debug version with a couple of prints and such. Can you try using this branch:

https://github.com/robohydra/robohydra/tree/proxy-debug

And run RoboHydra like so?

    robohydra -I examples/plugins examples/proxy-debug.conf

and make two requests like so:

    curl http://localhost:3000/http/
    curl http://localhost:3000/https/

Then you can send me the console output, plus robohydra.log. I can give you an e-mail address if you don't want to post publicly on GitHub.
